services:
  ftpserver:
    image: delfer/alpine-ftp-server:latest
    container_name: ftp
    ports:
      - "21:21"
      - "21000-21010:21000-21010"
    environment:
      - USERS=airflow|airflow
      - ADDRESS=127.0.0.1
    volumes:
      - ./data:/ftp/airflow
    networks:
      - landingzone
      - orchestration
networks:
  landingzone:
    external: true
  orchestration:
    external: true
